version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.1

jobs:
  check-and-build-only:
    executor: docker-publish/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker-publish/check
      - docker-publish/build

workflows:
  check_and_build_only:
    jobs:
      - check-and-build-only
  build_and_publish_docker_image:
    jobs:
      - docker-publish/publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          image: miyajan/prettier
          tag: $CIRCLE_TAG
